### ISSUE TITLE
Change Colormatic for Vanadium

### ISSUE THREAD

**Issue by GreenGrasst** [skywardmc/additive#48] opened 2024-01-09 22:30 UTC
**Is your request related to a problem? Please describe if so.**

Hello, for a long time I wanted to try a resource pack that I saw on YouTube, it's called faithless and it uses custom color settings, mob textures and other things that need optifine but I don't like it at all. Forge and I tried this modpack but the floor didn't work. It looked like the curseforge screenshots and I saw that it was because in 1.20.2 the colormatic mod does not work so I searched on reddit and found a mod called vanadium that solves that problem. (sorry if something is written wrong, I don't know English, I use Google Translate)

**Describe the mod you'd like to add, remove, or change**

Vanadium is a mod that replaces colormatic and adds the custom colors feature.

**Additional context**
Add any other context or screenshots about the request here.

mod link: https://modrinth.com/mod/vanadium

**Comment by intergrav** [comment] 2024-02-25 23:38
Duplicate of #44

**Closed by intergrav** 2024-02-25 23:38 UTC
Labels: enhancement
